<<<<<<< HEAD
<<<<<<< HEAD
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
<<<<<<< HEAD
<<<<<<< HEAD
import { Toaster } from 'sonner'
=======
import { Suspense } from 'react'
>>>>>>> 91fc705 (progress)
=======
>>>>>>> a530fbf (progress)

import './globals.css'
import { WebVitals } from '@/components/WebVitals'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Leo',
  description: 'Find all your projects here!',
  robots: 'noindex, nofollow',
<<<<<<< HEAD
}
=======
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
=======
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
>>>>>>> 94cc924 (update workflows)

import './globals.css'
import { WebVitals } from '@/components/WebVitals'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
};
>>>>>>> aab19bd (init)
=======
  title: 'Create Next App',
  description: 'Generated by create next app',
=======
>>>>>>> a530fbf (progress)
}
>>>>>>> 94cc924 (update workflows)

export default function RootLayout({
  children,
}: Readonly<{
<<<<<<< HEAD
<<<<<<< HEAD
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WebVitals />
<<<<<<< HEAD
<<<<<<< HEAD
        {children}
<<<<<<< HEAD
        <Toaster richColors theme="dark" />
=======

        <Suspense>{children}</Suspense>
>>>>>>> 91fc705 (progress)
=======
        {children}
>>>>>>> a530fbf (progress)
      </body>
    </html>
  )
=======
  children: React.ReactNode;
=======
  children: React.ReactNode
>>>>>>> 94cc924 (update workflows)
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
=======
      </body>
>>>>>>> ec8a0e3 (update progress)
    </html>
<<<<<<< HEAD
  );
>>>>>>> aab19bd (init)
=======
  )
>>>>>>> 94cc924 (update workflows)
}
